services:
  postgres:
    image: postgres

    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      
    ports:
      - 5432:5432

    volumes:
      - postgres_data:/var/lib/postgresql/data
  bookeeper:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 3000:3000

    env_file:
      - .env

    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres

    depends_on:
      - postgres

volumes:
  postgres_data: